name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      # Step 3: Cache pip packages to speed up builds
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # Step 5: Install Buildozer
      - name: Install Buildozer
        run: |
          pip install buildozer

      # Step 6: Install Android SDK dependencies
      - name: Install Android SDK
        run: |
          sudo apt-get install -y libncurses5 libtinfo5 libtinfo-dev zlib1g-dev openjdk-8-jdk
          yes | sdkmanager --licenses
          yes | sdkmanager --update

      # Step 7: Build the APK
      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      # Step 8: Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-debug.apk
          path: |
            ./bin/*.apk
