name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      # Step 3: Cache pip packages to speed up builds
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Install Buildozer
      - name: Install Buildozer
        run: |
          pip install buildozer

      # Step 6: Clean previous builds
      - name: Clean previous builds
        run: |
          buildozer appclean
          rm -rf ~/.buildozer

      # Step 7: Install Android SDK dependencies
      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5 libtinfo5 libtinfo-dev zlib1g-dev openjdk-8-jdk
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          # Accept licenses interactively
          echo "yes" | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --update

          # Install build-tools and platform-tools
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;30.0.3" "platforms;android-30" "extras;google;m2repository"

      # Step 8: Verify AIDL installation
      - name: Check for AIDL
        run: |
          if [ ! -f "$HOME/android-sdk/build-tools/30.0.3/aidl" ]; then
            echo "AIDL not found in the expected location"
            exit 1
          fi

      # Step 9: Build the APK
      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      # Step 10: Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-debug.apk
          path: |
            ./bin/*.apk
